import type { EmailData, EmailId } from './catalog'

/** Sample data for /styleguide/emails previews and render tests. */
export const emailFixtures: { [Id in EmailId]: EmailData[Id] } = {
  'verify-email': { name: 'Chiamaka', url: 'https://tokslearn.com/verify-email?token=example' },
  'sign-in-code': { code: '482913', expiresInMinutes: 10, device: 'Chrome on Android' },
  'reset-password': { name: 'Chiamaka', url: 'https://tokslearn.com/reset-password?token=example' },
  'password-changed': {
    name: 'Chiamaka',
    when: '2026-09-26T09:15:00.000Z',
    device: 'Safari on iPhone',
    resetUrl: 'https://tokslearn.com/forgot-password',
  },
  'new-sign-in': {
    name: 'Chiamaka',
    when: '2026-09-26T09:15:00.000Z',
    device: 'Chrome on Windows',
    ipHint: '102.89.x.x',
    securityUrl: 'https://tokslearn.com/account/settings/security',
  },
  'two-factor-changed': {
    name: 'Chiamaka',
    change: 'enabled',
    when: '2026-09-26T09:15:00.000Z',
    securityUrl: 'https://tokslearn.com/account/settings/security',
  },
  'email-changed-old': {
    name: 'Chiamaka',
    newEmail: 'c.okafor@example.com',
    cancelUrl: 'https://tokslearn.com/account/settings/security',
  },
  'deletion-requested': {
    name: 'Chiamaka',
    scheduledFor: '2026-10-10T09:15:00.000Z',
    cancelUrl: 'https://tokslearn.com/account/settings/privacy',
  },
  'data-export-ready': {
    name: 'Chiamaka',
    url: 'https://files.tokslearn.com/exports/example.zip',
    expiresAt: '2026-10-03T09:15:00.000Z',
  },
  'application-received': {
    name: 'Tobi',
    statusUrl: 'https://tokslearn.com/teach/apply',
  },
  'application-decision': {
    name: 'Tobi',
    approved: true,
    reason: null,
    reapplyOn: null,
    url: 'https://tokslearn.com/teach/courses',
  },
  'kyc-result': {
    name: 'Tobi',
    outcome: 'manual_review',
    applyUrl: 'https://tokslearn.com/teach/apply',
  },
  'payout-account-changed': {
    name: 'Tobi',
    bankName: 'Guaranty Trust Bank',
    last4: '4821',
    payoutsFrom: '2026-09-29T09:15:00.000Z',
    securityUrl: 'https://tokslearn.com/account/settings/security',
  },
  'course-review-decision': {
    name: 'Tobi',
    courseTitle: 'Excel for Accountants',
    approved: false,
    notes: 'Lesson 3 audio is very quiet. Please re-record it.\nAdd one preview lesson.',
    url: 'https://tokslearn.com/teach/courses/example/publish',
  },
  'order-receipt': {
    name: 'Amaka',
    publicId: 'TL-7K3M9Q2A',
    paidAt: '2026-10-01T09:30:00.000Z',
    items: [
      {
        title: 'Excel for Accountants',
        netKobo: '1350000',
        refundLine: 'Refunds until 8 October 2026, if you have watched less than 30%',
      },
      {
        title: 'Power BI Dashboards',
        netKobo: '2500000',
        refundLine: 'No refunds for this course',
      },
    ],
    subtotalKobo: '4000000',
    discountKobo: '150000',
    totalKobo: '3850000',
    paymentMethod: 'card',
    learnUrl: 'https://tokslearn.com/account',
    receiptUrl: 'https://tokslearn.com/account/orders/TL-7K3M9Q2A',
  },
  'enrollment-free': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    lessonCount: 12,
    duration: '2 h 40 min',
    certificate: 'Finish every lesson to get a certificate employers can check.',
    url: 'https://tokslearn.com/account',
  },
  'assignment-graded': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    assignmentTitle: 'Reconcile March',
    decision: 'graded',
    score: '18 / 20',
    passed: true,
    feedbackExcerpt:
      'Clean reconciliation. Label the bank charges next time so the reviewer can follow…',
    url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/01920000-0000-7000-8000-000000000002',
  },
  'certificate-issued': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    basisText: 'You passed the final exam',
    code: 'TL-C-8Q2M-4K7P',
    url: 'https://tokslearn.com/account/certificates',
    verifyUrl: 'https://tokslearn.com/verify/TL-C-8Q2M-4K7P',
    linkedInUrl:
      'https://www.linkedin.com/profile/add?startTask=CERTIFICATION_NAME&name=Bookkeeping%20for%20Small%20Businesses&organizationName=Tokslearn&issueYear=2026&issueMonth=9&certUrl=https%3A%2F%2Ftokslearn.com%2Fverify%2FTL-C-8Q2M-4K7P&certId=TL-C-8Q2M-4K7P',
  },
  'thread-reply': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    threadTitle: 'Where does VAT go in the cash book?',
    replierName: 'Tobi Adeleke',
    excerpt: 'Keep VAT in its own column so you can total it for the monthly return…',
    isAnswer: true,
    url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/community/01920000-0000-7000-8000-000000000009',
  },
  mention: {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    threadTitle: 'Month-end checklist',
    authorName: 'Bola A.',
    excerpt: '@amaka your template helped me close March in a day.',
    url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/community/01920000-0000-7000-8000-000000000009',
  },
  announcement: {
    courseTitle: 'Bookkeeping for Small Businesses',
    instructorName: 'Tobi Adeleke',
    cohortName: 'November 2026',
    title: 'Live review on Thursday',
    body: 'We meet on Thursday at 7pm to go through your March reconciliations.\n\nBring your workbook and one question.',
    url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/community/01920000-0000-7000-8000-000000000009',
  },
  'attempt-voided': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    examTitle: 'Final exam',
    reason: 'The exam was left for over 20 minutes, twice, in the middle of the attempt.',
    url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/01920000-0000-7000-8000-000000000003',
  },
  'monthly-statement': {
    name: 'Tobi',
    monthLabel: 'September 2026',
    sales: 23,
    shareKobo: '20251500',
    refundedKobo: '880500',
    paidOutKobo: '15000000',
    availableKobo: '9104000',
    url: 'https://tokslearn.com/teach/earnings',
  },
  'instructor-strike': {
    name: 'Tobi',
    rule: 'A3 Rights',
    reason: 'Lesson 4 uses a paid template pack without a licence.',
    active: 1,
    limit: 3,
    url: 'https://tokslearn.com/content-policy',
  },
  'payout-sent': {
    name: 'Tobi',
    amountKobo: '9104000',
    bankName: 'Guaranty Trust Bank',
    last4: '4821',
    monthLabel: 'October 2026',
    url: 'https://tokslearn.com/teach/earnings',
  },
  'payout-failed': {
    name: 'Tobi',
    amountKobo: '9104000',
    bankName: 'Guaranty Trust Bank',
    last4: '4821',
    monthLabel: 'October 2026',
    reason: 'Account closed',
    url: 'https://tokslearn.com/teach/settings',
  },
  'staff-payout-run-ready': {
    name: 'Funke',
    monthLabel: 'October 2026',
    totalKobo: '184250000',
    instructors: 37,
    held: 4,
    flagged: 2,
    payOnLabel: 'Monday 5 October',
    cosignRequired: false,
    url: 'https://tokslearn.com/admin/payouts/PR-2026-10',
  },
  'refund-update': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    outcome: 'denied',
    amountKobo: '1500000',
    reason: 'Refunds aren’t available after watching 30% of a course. You’ve watched 42%.',
    url: 'https://tokslearn.com/account/refunds',
    canAppeal: true,
  },
  'wishlist-price-drop': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    instructorName: 'Tobi Adeleke',
    oldKobo: '1500000',
    newKobo: '1050000',
    couponCode: 'MARCH30',
    endsAt: '2026-10-31T22:59:00.000Z',
    url: 'https://tokslearn.com/courses/bookkeeping-for-small-businesses',
    unsubscribeUrl:
      'https://tokslearn.com/unsubscribe?u=01920000-0000-7000-8000-000000000100&t=wishlist.price_drop&s=abc',
  },
  'activity-digest': {
    name: 'Amaka',
    count: 7,
    items: [
      {
        title: 'Bola A. replied to “Month-end checklist”',
        url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/community/01920000-0000-7000-8000-000000000009',
      },
      {
        title: 'Tobi Adeleke answered “Does this work in Excel 2016?”',
        url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/community/01920000-0000-7000-8000-000000000010',
      },
    ],
    url: 'https://tokslearn.com/account/notifications',
  },
  'new-review': {
    name: 'Tobi',
    courseTitle: 'Bookkeeping for Small Businesses',
    rating: 4,
    excerpt:
      'The bank reconciliation section saved me two days at month-end. I wanted more examples for VAT.',
    url: 'https://tokslearn.com/teach/reviews?course=01920000-0000-7000-8000-000000000301',
  },
  'live-reminder-24h': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    cohortName: 'November 2026',
    sessionTitle: 'Week 2: March reconciliations',
    hostName: 'Tobi Adeleke',
    when: 'Thursday 5 November at 7:00 pm',
    time: '7:00 pm',
    url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/live/01920000-0000-7000-8000-000000000011',
    calendarUrl:
      'https://calendar.google.com/calendar/render?action=TEMPLATE&text=Week+2&dates=20261105T180000Z%2F20261105T190000Z',
  },
  'live-reminder-15m': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    cohortName: 'November 2026',
    sessionTitle: 'Week 2: March reconciliations',
    hostName: 'Tobi Adeleke',
    when: 'Thursday 5 November at 7:00 pm',
    time: '7:00 pm',
    url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/live/01920000-0000-7000-8000-000000000011',
  },
  'lesson-unlocked': {
    name: 'Amaka',
    courseTitle: 'Bookkeeping for Small Businesses',
    lessons: ['Reconciling your bank statement', 'Month-end checklist'],
    url: 'https://tokslearn.com/learn/bookkeeping-for-small-businesses/01920000-0000-7000-8000-000000000001',
  },
}
